version: '3.7'
services:
  postgres:
    container_name: postgres_container
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      gbox-net:
        aliases:
          - database.gbox-net.local.vpc
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

#  transaction-app:
#    container_name: gbox-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    #    image: transaction-app:latest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://database.gbox-net.local.vpc:5432/postgres
#    ports:
#      - 8787:8787
#    restart: always
#    networks:
#      - gbox-net
#    depends_on:
#      - postgres

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - gbox-net
#    restart: unless-stopped

networks:
  gbox-net:

volumes:
  postgres:
  pgadmin: